name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t background-remover:${{ github.sha }} .
    
    - name: Verify image was created
      run: |
        docker images | grep background-remover
    
    - name: Success
      run: echo "✅ Docker image built successfully!"
