cd /Users/fais/Desktop/rm_bg

cat > .github/workflows/docker-build.yml << 'EOF'
name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t background-remover:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 --name test-app background-remover:${{ github.sha }}
        echo "Waiting for app to start..."
        sleep 30
        echo "Checking Docker logs..."
        docker logs test-app
        echo "Checking if app is responding..."
        curl -v http://localhost:8000 || exit 1
        docker stop test-app
    
    - name: Show logs on failure
      if: failure()
      run: docker logs test-app
    
    - name: Success
      run: echo "✅ Docker image built and tested successfully!"
EOF